apiVersion: apps/v1
kind: Deployment
metadata:
  name: edusport-connect-frontend
  namespace: {{ include "esc.namespace" . }}
  labels:
    {{- include "esc.labels" . | nindent 4 }}
    {{- include "esc.frontend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.frontend.strategy.rollingUpdate.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.frontend.strategy.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      {{- include "esc.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "esc.frontend.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101    # user nginx dans l'image officielle alpine
        fsGroup: 101
      containers:
        - name: nginx
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.frontend.port }}
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
