apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: edusport-connect-ingress
  namespace: {{ include "esc.namespace" . }}
  labels:
    {{- include "esc.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    - match: "Host(`{{ .Values.domain }}`) || Host(`www.{{ .Values.domain }}`)"
      kind: Rule
      services:
        - name: edusport-connect-frontend-service
          port: 80
      middlewares:
        - name: security-headers
        {{- if .Values.ingress.crowdsec }}
        - name: crowdsec-bouncer
          namespace: kube-system
        {{- end }}
